# ==========================================
# SERVER
# ==========================================
server.port=8080

# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/university_portal
spring.datasource.username=postgres
spring.datasource.password=19112002

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# JWT
# ==========================================
jwt.secret=university_portal_secret_key_must_be_at_least_256_bits_long_for_hs256
jwt.expiration.access=900000
jwt.expiration.refresh=604800000

# ==========================================
# HR CV FILE STORAGE
# ==========================================
hr.cv.storage.upload-dir=uploads/hr-cv
hr.cv.storage.max-bytes=10485760